backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('kino/', include('kino.urls', namespace='kino')),
    path('pirate/', include('pirate.urls', namespace='pirate')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/homework/urls.py
from django.urls import path
from homework import views

app_name = 'homework'

urlpatterns = [
    path('', views.index, name='home'),
]

backend/kino/urls.py
from django.urls import path
from kino import views

app_name = 'kino'

urlpatterns = [
    path('', views.base, name='home'),
]

backend/pirate/urls.py
from django.urls import path
from pirate.views import list_reestr, reestr_detail

app_name = 'pirate'

urlpatterns = [
    path('', list_reestr ,name='list_reestr'),
    path("reestr-detail/<int:pk>/", reestr_detail, name='reestr_detail'),

]

backend/kino/models.py
from django.db import models

backend/pirate/models.py
from django.db import models

 
class Reestr(models.Model):
    title = models.CharField("Название", max_length=256)
    description = models.TextField("Описание", blank=True, null=True)
    url = models.URLField("URL адрес")

    def __str__(self) -> str:
        return self.title

backend/kino/views.py
from django.http import request
from django.shortcuts import render

def base(request):
    return render(request, "kino/base.html")

backend/pirate/views.py
import requests
from django.shortcuts import render

from pirate.models import Reestr


def list_reestr(request):
    """Вывод списка всех адресов"""

    reestr = Reestr.objects.all()
    return render(request, "pirate/reestr_list.html", context={"reestr": reestr})


def reestr_detail(request, pk):
    """Вывод детальных данных"""

    book = Reestr.objects.get(pk=pk)
    response = requests.get(book.url)
    data = response.json()

    data = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"data": data})

def gog_list(request):
    response = requests.get("https://hydralinks.cloud/sources/gog.json")
    data = response.json()

    gog = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"gog": gog})


def atopgames_list(request):
    response = requests.get("https://hydralinks.cloud/sources/atop-games.json")
    data = response.json()

    atopgames = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"atopgames": atopgames})


def steamsoft_list(request):
    response = requests.get("https://hydralinks.cloud/sources/steamrip-software.json")
    data = response.json()

    steamsoft = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"steamsoft": steamsoft})


def steamrip_list(request):
    response = requests.get("https://hydralinks.cloud/sources/steamrip.json")
    data = response.json()

    steamrip = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"steamrip": steamrip})


def dodi_list(request):
    response = requests.get("https://hydralinks.cloud/sources/dodi.json")
    data = response.json()

    dodi = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"dodi": dodi})


def empress_list(request):
    response = requests.get("https://hydralinks.cloud/sources/empress.json")
    data = response.json()

    empress = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"empress": empress})


def fitgirl_list(request):
    response = requests.get("https://hydralinks.cloud/sources/fitgirl.json")
    data = response.json()

    fitgirl = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"fitgirl": fitgirl})


def kaoskrew_list(request):
    response = requests.get("https://hydralinks.cloud/sources/kaoskrew.json")
    data = response.json()

    kaoskrew = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"kaoskrew": kaoskrew})


def onlinefix_list(request):
    response = requests.get("https://hydralinks.cloud/sources/onlinefix.json")
    data = response.json()

    onlinefix = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"onlinefix": onlinefix})


def tinyrepacks_list(request):
    response = requests.get("https://hydralinks.cloud/sources/tinyrepacks.json")
    data = response.json()

    tinyrepacks = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"tinyrepacks": tinyrepacks})


def xatab_list(request):
    response = requests.get("https://hydralinks.cloud/sources/xatab.json")
    data = response.json()

    xatab = data.get("downloads", [])
    return render(request, "pirate/pirate_list.html", {"tinyrepacks": xatab})

backend/kino/templates/kino/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
    {% block content %}
    <div class="card">
        <div class="card-body">
          This is some text within a card body.
        </div>
      </div>
    {% endblock %}
</body>
</html>

backend/pirate/templates/pirate/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">Test</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pirate:list_reestr' %}">Пиратская Бухта</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>    
</body>
</html>

backend/pirate/templates/pirate/pirate_list.html
{% extends 'pirate/base.html' %}

{% block title %}Список Репаков{% endblock %}

{% block content %}
<h1>Список Репаков</h1>
<ul class="list-group">
    {% for download in downloads %}
        <li class="list-group-item">
            <strong>{{ download.title }}</strong> ({{ download.fileSize }}) 
            <br>
            <a href="{{ download.uris.0 }}" target="_blank" class="btn btn-primary">Скачать</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

backend/pirate/templates/pirate/reestr_list.html
{% extends 'pirate/base.html' %}

{% block title %}Список Репаков{% endblock %}

{% block content %}
<h1>Список Репаков</h1>
<ul class="list-group">
    {% for r in reestr %}
        <li class="list-group-item">
            <strong>{{ r.title }}</strong> ({{ r.title }}) 
            <br>
            <a href="{% url 'pirate:reestr_detail' pk=r.pk %}" target="_blank" class="btn btn-primary">Скачать</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}